import {
    BadgeCheck,
    BarChart3,
    Bitcoin,
    Blocks,
    BookOpen,
    Bot,
    Box,
    Braces,
    BriefcaseBusiness,
    CalendarDays,
    Camera,
    Clapperboard,
    Cloud,
    Code2,
    Database,
    DraftingCompass,
    Facebook,
    GalleryVerticalEnd,
    Gamepad2,
    Github,
    Globe,
    GraduationCap,
    HardDrive,
    Headphones,
    HeartPulse,
    Instagram,
    Landmark,
    LayoutTemplate,
    Linkedin,
    Megaphone,
    MessagesSquare,
    Newspaper,
    Palette,
    PanelsTopLeft,
    PencilRuler,
    Scale,
    ShieldCheck,
    ShoppingBag,
    Smartphone,
    Twitch,
    Users,
    Workflow,
    type LucideIcon,
} from 'lucide-react';
import Image from 'next/image';
import type { SocialPresenceIconKey } from '@/lib/profile/normalization';

const ICONS: Partial<Record<SocialPresenceIconKey, LucideIcon>> = {
    github: Github,
    linkedin: Linkedin,
    instagram: Instagram,
    twitch: Twitch,
    facebook: Facebook,
    uxpin: PanelsTopLeft,
    mobbin: PanelsTopLeft,
    uxfolio: GalleryVerticalEnd,
    readymag: LayoutTemplate,
    cargo: LayoutTemplate,
    carbonmade: Palette,
    coroflot: BriefcaseBusiness,
    contra: BriefcaseBusiness,
    spline: Box,
    balsamiq: PencilRuler,
    ai: Bot,
    analytics: BarChart3,
    api: Braces,
    audio: Headphones,
    automation: Workflow,
    business: BriefcaseBusiness,
    careers: BadgeCheck,
    cloud: Cloud,
    code: Code2,
    community: Users,
    commerce: ShoppingBag,
    communication: MessagesSquare,
    data: Database,
    docs: BookOpen,
    education: GraduationCap,
    engineering: DraftingCompass,
    events: CalendarDays,
    finance: Landmark,
    gaming: Gamepad2,
    health: HeartPulse,
    legal: Scale,
    marketing: Megaphone,
    mobile: Smartphone,
    'no-code': Blocks,
    photography: Camera,
    security: ShieldCheck,
    storage: HardDrive,
    video: Clapperboard,
    web3: Bitcoin,
    writing: Newspaper,
    globe: Globe,
};

const BRAND_ASSETS: Partial<Record<SocialPresenceIconKey, string>> = {
    discord: '/skill-icons/v1/discord.svg',
    figma: '/skill-icons/v1/figma.svg',
    slack: '/skill-icons/v1/devicon-slack.svg',
    notion: '/skill-icons/v1/notion.svg',
    youtube: '/social-icons/youtube.svg',
    'google-scholar': '/social-icons/google-scholar.svg',
    researchgate: '/social-icons/researchgate.svg',
    orcid: '/social-icons/orcid.svg',
    arxiv: '/social-icons/arxiv.svg',
    doi: '/social-icons/doi.svg',
    'semantic-scholar': '/social-icons/semantic-scholar.svg',
    academia: '/social-icons/academia.svg',
    pubmed: '/social-icons/pubmed.svg',
    zenodo: '/social-icons/zenodo.svg',
    mendeley: '/social-icons/mendeley.svg',
    gitlab: '/skill-icons/v1/gitlab.svg',
    bitbucket: '/skill-icons/v1/bitbucket.svg',
    stackoverflow: '/skill-icons/v1/stackoverflow.svg',
    codepen: '/skill-icons/v1/devicon-codepen.svg',
    dribbble: '/social-icons/dribbble.svg',
    bluesky: '/social-icons/bluesky.svg',
    mastodon: '/social-icons/mastodon.svg',
    threads: '/social-icons/threads.svg',
    behance: '/social-icons/behance.svg',
    medium: '/social-icons/medium.svg',
    substack: '/social-icons/substack.svg',
    reddit: '/social-icons/reddit.svg',
    tiktok: '/social-icons/tiktok.svg',
    framer: '/skill-icons/v1/framer.svg',
    webflow: '/skill-icons/v1/webflow.svg',
    canva: '/skill-icons/v1/devicon-canva.svg',
    sketch: '/skill-icons/v1/sketch.svg',
    zeplin: '/skill-icons/v1/logos-zeplin.svg',
    invision: '/skill-icons/v1/logos-invision-icon.svg',
    miro: '/skill-icons/v1/miro.svg',
    'proto-io': '/social-icons/proto-io.svg',
    'adobe-portfolio': '/skill-icons/v1/logos-adobe-icon.svg',
    pinterest: '/social-icons/pinterest.svg',
    awwwards: '/social-icons/awwwards.svg',
    loom: '/social-icons/loom.svg',
    penpot: '/social-icons/penpot.svg',
    rive: '/skill-icons/v1/rive.svg',
    maze: '/social-icons/maze.svg',
    // ponytail: Version the corrected glyph so browsers cannot reuse the earlier blue asset.
    heliyon: '/social-icons/heliyon.svg?v=20260830-2',
};

const COLOR_ASSETS = new Set<SocialPresenceIconKey>(['slack', 'canva', 'zeplin', 'invision', 'adobe-portfolio']);

export function SocialPresenceIcon({ iconKey, className = 'h-4 w-4' }: {
    iconKey: SocialPresenceIconKey | null;
    className?: string;
}) {
    if (!iconKey) return null;
    if (iconKey === 'x') return <span aria-hidden="true" className={`${className} inline-flex items-center justify-center font-semibold leading-none`}>𝕏</span>;
    const asset = BRAND_ASSETS[iconKey];
    if (asset) return <Image src={asset} alt="" aria-hidden="true" width={16} height={16} unoptimized className={`${className} object-contain ${COLOR_ASSETS.has(iconKey) ? '' : 'dark:invert'}`} />;
    const Icon = ICONS[iconKey];
    return Icon ? <Icon aria-hidden="true" className={className} /> : null;
}
