import { normalizeSkillLookup, skillSlug } from './normalization'
import type { SkillSemanticIconKey } from './semantic-icons'
import type {
    MarketSkillDefinition,
    SkillCategoryDefinition,
    SkillKind,
    SkillMarketTier,
    SkillSearchResult,
} from './types'

export const SKILL_CATALOG_VERSION = '1.3.7' as const
export const SKILL_ICON_SOURCE_VERSION = '16.24.1' as const
export const SKILL_DEVICON_SOURCE_VERSION = '2.17.0' as const
export const SKILL_CATALOG_MIGRATION_TAG = '0117_market_skill_catalog_1_3_6' as const

export const SKILL_CATEGORIES: readonly SkillCategoryDefinition[] = [
    { key: 'programming', name: 'Programming', description: 'Programming, scripting, and markup languages.', iconKey: 'code-2', displayOrder: 10 },
    { key: 'frontend', name: 'Frontend', description: 'Web UI frameworks, libraries, styling, and build tools.', iconKey: 'panels-top-left', displayOrder: 20 },
    { key: 'backend', name: 'Backend & APIs', description: 'Server frameworks, API styles, and distributed application patterns.', iconKey: 'server-cog', displayOrder: 30 },
    { key: 'mobile', name: 'Mobile', description: 'Native and cross-platform mobile application development.', iconKey: 'smartphone', displayOrder: 40 },
    { key: 'data', name: 'Data & Databases', description: 'Databases, streaming, warehousing, and data engineering.', iconKey: 'database', displayOrder: 50 },
    { key: 'geospatial', name: 'Geospatial & Mapping', description: 'GIS, mapping, spatial databases, and earth-observation tools.', iconKey: 'map', displayOrder: 55 },
    { key: 'ai', name: 'AI & Machine Learning', description: 'Machine learning, generative AI, model operations, and evaluation.', iconKey: 'brain-circuit', displayOrder: 60 },
    { key: 'cloud', name: 'Cloud Platforms', description: 'Cloud, serverless, hosting, and edge platforms.', iconKey: 'cloud-cog', displayOrder: 70 },
    { key: 'developer-tools', name: 'Developer Tools & Collaboration', description: 'Source control, IDEs, developer platforms, API tools, and team collaboration.', iconKey: 'wrench', displayOrder: 75 },
    { key: 'operating-systems', name: 'Operating Systems', description: 'Desktop, server, mobile, and specialist operating-system ecosystems.', iconKey: 'cpu', displayOrder: 78 },
    { key: 'devops', name: 'DevOps & SRE', description: 'Delivery, infrastructure, reliability, and observability.', iconKey: 'workflow', displayOrder: 80 },
    { key: 'security', name: 'Security', description: 'Application, infrastructure, identity, risk, and compliance security.', iconKey: 'shield-check', displayOrder: 90 },
    { key: 'quality', name: 'Testing & Quality', description: 'Quality engineering, testing practices, and testing tools.', iconKey: 'badge-check', displayOrder: 100 },
    { key: 'design', name: 'Design & Creative', description: 'Product, visual, interaction, motion, and creative design.', iconKey: 'palette', displayOrder: 110 },
    { key: 'product', name: 'Product & Delivery', description: 'Product strategy, discovery, delivery, and collaboration.', iconKey: 'map', displayOrder: 120 },
    { key: 'analytics', name: 'Analytics & BI', description: 'Business intelligence, product analytics, and experimentation.', iconKey: 'chart-no-axes-combined', displayOrder: 130 },
    { key: 'games', name: 'Games, Graphics & XR', description: 'Game engines, graphics, spatial computing, and 3D production.', iconKey: 'gamepad-2', displayOrder: 140 },
    { key: 'scientific-engineering', name: 'Scientific Computing & Engineering', description: 'Engineering simulation, scientific computing, CAD/CAE, and technical design.', iconKey: 'orbit', displayOrder: 145 },
    { key: 'embedded', name: 'Embedded, IoT & Robotics', description: 'Firmware, hardware, robotics, and connected devices.', iconKey: 'cpu', displayOrder: 150 },
    { key: 'blockchain', name: 'Blockchain', description: 'Distributed ledgers, smart contracts, and Web3 ecosystems.', iconKey: 'blocks', displayOrder: 160 },
    { key: 'enterprise', name: 'Enterprise & Automation', description: 'Enterprise platforms, low-code tools, and workflow automation.', iconKey: 'building-2', displayOrder: 170 },
    { key: 'growth', name: 'Marketing & Growth', description: 'Acquisition, content, lifecycle, and community growth.', iconKey: 'megaphone', displayOrder: 180 },
    { key: 'business', name: 'Business & Operations', description: 'Sales, finance, people, customer, legal, and operating skills.', iconKey: 'briefcase-business', displayOrder: 190 },
    { key: 'human', name: 'Human Skills', description: 'Transferable collaboration, communication, and leadership competencies.', iconKey: 'users-round', displayOrder: 200 },
    { key: 'domain', name: 'Industry Knowledge', description: 'Specialized industry and market domain knowledge.', iconKey: 'landmark', displayOrder: 210 },
] as const

type SkillGroup = {
    categoryKey: string
    kind: SkillKind
    tier: SkillMarketTier
    names: string
}

const GROUPS: readonly SkillGroup[] = [
    { categoryKey: 'programming', kind: 'language', tier: 'core', names: 'JavaScript|TypeScript|Python|Java|C#|C++|C|Go|Rust|PHP|Ruby|Swift|Kotlin|Dart|Scala|R|SQL|HTML|CSS|Bash|PowerShell|MATLAB|Julia|Lua|Elixir|Erlang|Haskell|Clojure|F#|Objective-C|Solidity|Zig|Assembly|Groovy|Perl|COBOL|Fortran' },
    { categoryKey: 'programming', kind: 'language', tier: 'extended', names: 'Sass|Less|XML|Markdown|HCL|Nix|OCaml|Crystal|Nim|Odin|Delphi|Visual Basic|Apex' },
    { categoryKey: 'programming', kind: 'language', tier: 'extended', names: 'Ada|ABAP|Elm|GDScript|Gleam|Lisp|MicroPython|Mojo|Prolog|Racket|SystemVerilog|Verilog|VHDL|VBA|Wolfram Language' },
    { categoryKey: 'frontend', kind: 'framework', tier: 'core', names: 'React|Next.js|Vue.js|Nuxt|Angular|Svelte|SvelteKit|Astro|Remix|SolidJS|Qwik|Lit|Web Components' },
    { categoryKey: 'frontend', kind: 'library', tier: 'core', names: 'Tailwind CSS|Bootstrap|Material UI|Chakra UI|Ant Design|shadcn/ui|Redux|Zustand|TanStack Query|RxJS|Storybook|D3.js|Three.js' },
    { categoryKey: 'frontend', kind: 'tool', tier: 'core', names: 'Vite|Webpack|Rollup|Babel|ESLint|Prettier|npm|pnpm|Yarn|Bun' },
    { categoryKey: 'frontend', kind: 'framework', tier: 'extended', names: 'Alpine.js|AngularJS|Backbone.js|Ember.js|htmx|jQuery|Leptos|Preact|Stencil|Stimulus' },
    { categoryKey: 'frontend', kind: 'library', tier: 'extended', names: 'Emotion|GSAP|Mantine|MobX|React Hook Form|React Router|Styled Components|SWR|UnoCSS' },
    { categoryKey: 'frontend', kind: 'tool', tier: 'extended', names: 'esbuild|Parcel|Rspack|SWC|Turborepo|Nx' },
    { categoryKey: 'backend', kind: 'platform', tier: 'core', names: 'Node.js|Deno|Bun Runtime' },
    { categoryKey: 'backend', kind: 'framework', tier: 'core', names: 'Express|NestJS|Fastify|Django|Flask|FastAPI|Spring Boot|ASP.NET Core|Ruby on Rails|Laravel|Symfony|Phoenix|Gin|Fiber|Actix Web' },
    { categoryKey: 'backend', kind: 'protocol', tier: 'core', names: 'REST APIs|GraphQL|gRPC|WebSockets|tRPC|OpenAPI|OAuth 2.0|OpenID Connect' },
    { categoryKey: 'backend', kind: 'methodology', tier: 'extended', names: 'Microservices|Event-Driven Architecture|Domain-Driven Design|CQRS|Event Sourcing|Server-Side Rendering|API Design|Distributed Systems' },
    { categoryKey: 'backend', kind: 'framework', tier: 'extended', names: 'AdonisJS|ASP.NET|Axum|Blazor|CakePHP|CodeIgniter|Drupal|Fresh|Hono|Koa|Micronaut|Odoo|Quarkus|Strapi|WordPress' },
    { categoryKey: 'backend', kind: 'protocol', tier: 'extended', names: 'Apache Thrift|JSON:API|Message Queues|SOAP|Webhooks' },
    { categoryKey: 'backend', kind: 'platform', tier: 'extended', names: 'Electron|Tauri' },
    { categoryKey: 'mobile', kind: 'platform', tier: 'core', names: 'iOS|Android|React Native|Expo|Flutter|Kotlin Multiplatform|Ionic|Capacitor|.NET MAUI' },
    { categoryKey: 'mobile', kind: 'framework', tier: 'core', names: 'SwiftUI|UIKit|Jetpack Compose|Android SDK|Core Data|Room' },
    { categoryKey: 'mobile', kind: 'tool', tier: 'core', names: 'Android Studio|Xcode|Firebase Cloud Messaging|Google Play Console|TestFlight' },
    { categoryKey: 'mobile', kind: 'framework', tier: 'extended', names: 'NativeScript|Xamarin|Android Jetpack|Compose Multiplatform|MapKit|HealthKit|StoreKit|Core ML|Material 3' },
    { categoryKey: 'mobile', kind: 'library', tier: 'extended', names: 'Realm' },
    { categoryKey: 'mobile', kind: 'platform', tier: 'extended', names: 'App Store Connect|Wear OS|Android TV|CarPlay|Samsung Galaxy Store|Huawei AppGallery' },
    { categoryKey: 'mobile', kind: 'tool', tier: 'extended', names: 'CocoaPods|Fastlane|Swift Package Manager|Firebase App Distribution|Android NDK|FlutterFlow' },
    { categoryKey: 'data', kind: 'database', tier: 'core', names: 'PostgreSQL|MySQL|Microsoft SQL Server|SQLite|Oracle Database|MongoDB|Redis|Amazon DynamoDB|Apache Cassandra|CockroachDB|Supabase|Firebase|Cloud Firestore|Elasticsearch|OpenSearch|Neo4j|ClickHouse|Snowflake|Google BigQuery' },
    { categoryKey: 'data', kind: 'platform', tier: 'core', names: 'Databricks|dbt|Apache Airflow|Apache Kafka|Apache Spark|Apache Flink|Apache Hadoop|Apache Beam|Trino|Presto|DuckDB' },
    { categoryKey: 'data', kind: 'competency', tier: 'extended', names: 'Data Engineering|Data Modeling|ETL|ELT|Data Warehousing|Data Governance|Data Quality|Streaming Data|Database Administration|Query Optimization' },
    { categoryKey: 'data', kind: 'database', tier: 'core', names: 'Amazon Aurora|Amazon Redshift|Azure Cosmos DB|Azure SQL Database|Couchbase|CouchDB|Firebase Realtime Database|IBM Db2|InfluxDB|MariaDB|Neon|PocketBase|Qdrant|TimescaleDB|Valkey' },
    { categoryKey: 'data', kind: 'database', tier: 'extended', names: 'Datomic|Firebird|H2|PlanetScale|QuestDB|SingleStore|SurrealDB|TiDB|YugabyteDB' },
    { categoryKey: 'data', kind: 'tool', tier: 'core', names: 'Airbyte|Fivetran|Great Expectations|Pandas|Polars|Prisma|Drizzle ORM' },
    { categoryKey: 'data', kind: 'platform', tier: 'extended', names: 'Apache Hudi|Apache Iceberg|Dagster|Delta Lake|Meltano|Prefect' },
    { categoryKey: 'data', kind: 'competency', tier: 'extended', names: 'Vector Databases|Data Lakehouse|Data Mesh' },
    { categoryKey: 'ai', kind: 'competency', tier: 'core', names: 'Machine Learning|Deep Learning|Generative AI|Large Language Models|Retrieval-Augmented Generation|AI Agents|Natural Language Processing|Computer Vision|Recommendation Systems|Prompt Engineering|Model Evaluation|Feature Engineering|MLOps|Responsible AI' },
    { categoryKey: 'ai', kind: 'framework', tier: 'core', names: 'PyTorch|TensorFlow|Keras|scikit-learn|JAX|Hugging Face|LangChain|LlamaIndex|MLflow|Kubeflow' },
    { categoryKey: 'ai', kind: 'platform', tier: 'core', names: 'OpenAI API|Amazon Bedrock|Azure AI|Google Vertex AI|Pinecone|Weaviate|Milvus|Chroma|pgvector' },
    { categoryKey: 'ai', kind: 'framework', tier: 'core', names: 'AutoGen|CrewAI|DSPy|Haystack|LangGraph|Ollama|Pydantic AI|Semantic Kernel|Sentence Transformers|spaCy|XGBoost' },
    { categoryKey: 'ai', kind: 'framework', tier: 'extended', names: 'CatBoost|Gradio|LightGBM|llama.cpp|NLTK|ONNX|OpenCV|Ray|Streamlit|Ultralytics|vLLM' },
    { categoryKey: 'ai', kind: 'platform', tier: 'core', names: 'Claude|Cohere|DeepSeek|Gemini|Groq|Llama|Mistral AI|Qwen|Replicate|Together AI' },
    { categoryKey: 'ai', kind: 'platform', tier: 'extended', names: 'Comet ML|DVC|Feast|Modal|Neptune|Weights & Biases' },
    { categoryKey: 'ai', kind: 'competency', tier: 'extended', names: 'Embeddings|Fine-Tuning|Foundation Models|Multimodal AI|Synthetic Data|TinyML' },
    { categoryKey: 'ai', kind: 'library', tier: 'extended', names: 'MiniLM' },
    { categoryKey: 'ai', kind: 'protocol', tier: 'core', names: 'Model Context Protocol|Agent2Agent Protocol' },
    { categoryKey: 'ai', kind: 'framework', tier: 'core', names: 'OpenAI Agents SDK|Google Agent Development Kit|Amazon Bedrock Agents' },
    { categoryKey: 'ai', kind: 'platform', tier: 'core', names: 'Azure AI Foundry|Google AI Studio|OpenRouter|Perplexity API|Cerebras|SambaNova|Fireworks AI|Baseten|Anyscale|Runpod' },
    { categoryKey: 'ai', kind: 'platform', tier: 'extended', names: 'Stability AI|Midjourney|ElevenLabs|AssemblyAI|Vapi|Retell AI' },
    { categoryKey: 'ai', kind: 'tool', tier: 'core', names: 'LangSmith|Langfuse|Arize Phoenix|Promptfoo|Ragas|DeepEval|Guardrails AI|LiteLLM' },
    { categoryKey: 'ai', kind: 'framework', tier: 'extended', names: 'TensorRT|OpenVINO|BentoML|Seldon Core|KServe' },
    { categoryKey: 'ai', kind: 'platform', tier: 'core', names: 'Meta AI|Moonshot AI|NotebookLM|ModelScope|DeepMind|Dataiku|Clarifai|Deepgram|Databricks Mosaic AI|Snowflake Cortex AI|IBM watsonx|Cloudflare Workers AI|NVIDIA NIM|NVIDIA NeMo|Amazon SageMaker AI|Azure Machine Learning|Google Vertex AI Agent Engine|GroqCloud' },
    { categoryKey: 'ai', kind: 'framework', tier: 'core', names: 'Dify|Langflow|Vercel AI SDK|Google Genkit|Microsoft Agent Framework|OpenAI Swarm|smolagents' },
    { categoryKey: 'ai', kind: 'tool', tier: 'extended', names: 'LM Studio|Braintrust|OpenAI Evals|Text Generation Inference' },
    { categoryKey: 'cloud', kind: 'platform', tier: 'core', names: 'Amazon Web Services|Microsoft Azure|Google Cloud|Cloudflare|Vercel|Netlify|Heroku|DigitalOcean|OpenStack|Render|Fly.io' },
    { categoryKey: 'cloud', kind: 'methodology', tier: 'core', names: 'Serverless Computing|Edge Computing|Cloud Architecture|Cloud Migration|Multi-Cloud|FinOps' },
    { categoryKey: 'cloud', kind: 'platform', tier: 'extended', names: 'Cloud Foundry|Firebase Hosting|IBM Cloud|Oracle Cloud Infrastructure|Railway|Yandex Cloud' },
    { categoryKey: 'cloud', kind: 'platform', tier: 'core', names: 'Amazon RDS|AWS Lambda|Azure Functions|Cloudflare Workers|Google Cloud Run' },
    { categoryKey: 'cloud', kind: 'library', tier: 'extended', names: 'AWS SDK|Azure SDK|Google Cloud SDK' },
    { categoryKey: 'developer-tools', kind: 'platform', tier: 'core', names: 'GitHub|GitLab|Bitbucket|Azure DevOps|Git|Subversion|Perforce' },
    { categoryKey: 'developer-tools', kind: 'tool', tier: 'core', names: 'Visual Studio Code|Visual Studio|IntelliJ IDEA|PyCharm|WebStorm|PhpStorm|Rider|Cursor|Vim|Neovim|Sublime Text|Eclipse|JupyterLab' },
    { categoryKey: 'developer-tools', kind: 'tool', tier: 'extended', names: 'VSCodium|Notepad++|Zed|Windsurf|Nano|GitKraken|Sourcetree|DBeaver|DataGrip' },
    { categoryKey: 'developer-tools', kind: 'platform', tier: 'core', names: 'GitHub Copilot|Claude Code|Insomnia|Bruno|Swagger UI|GitHub Codespaces|Dev Containers' },
    { categoryKey: 'developer-tools', kind: 'platform', tier: 'extended', names: 'Aider|Bolt|Cline|Lovable|Roo Code|Trae' },
    { categoryKey: 'developer-tools', kind: 'platform', tier: 'core', names: 'Codex|Google Antigravity|OpenCode|Continue|Kiro|Devin|Replit Agent|Sourcegraph Cody|Tabnine|Amazon Q Developer|JetBrains AI Assistant|Augment Code|CodeRabbit|Factory|v0|Warp|Qwen Code' },
    { categoryKey: 'developer-tools', kind: 'platform', tier: 'core', names: 'Chrome Extension API|Chrome DevTools|Chrome Web Store|Firefox Add-ons|Safari Web Extensions|WebExtensions API' },
    { categoryKey: 'developer-tools', kind: 'tool', tier: 'core', names: 'Discord|Google Workspace|Lucidchart|Microsoft Teams|Miro|Obsidian|Slack|Stack Overflow for Teams|Zoom' },
    { categoryKey: 'developer-tools', kind: 'tool', tier: 'extended', names: 'Coda|Doxygen|Redmine|YouTrack' },
    { categoryKey: 'devops', kind: 'tool', tier: 'core', names: 'Docker|Docker Compose|Kubernetes|Helm|Terraform|Pulumi|Ansible|GitHub Actions|GitLab CI/CD|Jenkins|CircleCI|Argo CD|Flux|Prometheus|Grafana|Datadog|New Relic|OpenTelemetry|Elastic Stack|NGINX' },
    { categoryKey: 'devops', kind: 'competency', tier: 'core', names: 'Site Reliability Engineering|Platform Engineering|Infrastructure as Code|CI/CD|Observability|Incident Response|Release Engineering|Systems Administration|Computer Networking' },
    { categoryKey: 'devops', kind: 'tool', tier: 'core', names: 'Bazel|Cargo|Composer|Gradle|Homebrew|GNU Make|Maven|NuGet|Pip|Poetry|Podman' },
    { categoryKey: 'devops', kind: 'tool', tier: 'extended', names: 'APT|Chocolatey|MSBuild|Ninja|OpenTofu|Vagrant|Yarn Berry' },
    { categoryKey: 'devops', kind: 'platform', tier: 'core', names: 'Consul|Envoy|HashiCorp Vault|Istio|Jaeger|Loki|Nomad|Packer|Rancher|Sentry|Splunk|Tempo|Traefik' },
    { categoryKey: 'devops', kind: 'platform', tier: 'extended', names: 'HAProxy|Linkerd|Opsgenie|PagerDuty' },
    { categoryKey: 'security', kind: 'competency', tier: 'core', names: 'Application Security|Cloud Security|Identity and Access Management|Penetration Testing|Threat Modeling|Vulnerability Management|Security Operations|Zero Trust|Cryptography|Secure Coding|Digital Forensics|Network Security|DevSecOps|Security Architecture' },
    { categoryKey: 'security', kind: 'domain', tier: 'extended', names: 'SOC 2|ISO 27001|GDPR|HIPAA|PCI DSS|NIST Cybersecurity Framework|SIEM|Data Privacy|Risk Management' },
    { categoryKey: 'security', kind: 'tool', tier: 'core', names: 'Auth0|Burp Suite|Dependabot|GitHub Advanced Security|Keycloak|Metasploit|Nmap|Okta|Open Policy Agent|OWASP|Semgrep|Snyk|SonarQube|Trivy|Wireshark' },
    { categoryKey: 'security', kind: 'tool', tier: 'extended', names: 'Falco|Kali Linux|Nessus|Wazuh|1Password' },
    { categoryKey: 'quality', kind: 'competency', tier: 'core', names: 'Manual Testing|Test Automation|Unit Testing|Integration Testing|End-to-End Testing|Contract Testing|Accessibility Testing|Performance Testing|Load Testing|Mobile Testing|API Testing|Quality Engineering' },
    { categoryKey: 'quality', kind: 'tool', tier: 'core', names: 'Playwright|Cypress|Selenium|Jest|Vitest|pytest|JUnit|Postman|k6|Apache JMeter|Appium|Cucumber' },
    { categoryKey: 'quality', kind: 'tool', tier: 'core', names: 'BrowserStack|Chromatic|Codecov|Mocha|Pact|Percy|Puppeteer|Robot Framework|Sauce Labs|Storybook Test' },
    { categoryKey: 'quality', kind: 'tool', tier: 'extended', names: 'Artillery|Gatling|Jasmine|Karma|LambdaTest|Locust|NUnit|PHPUnit|RSpec|TestNG|WireMock|xUnit' },
    { categoryKey: 'design', kind: 'tool', tier: 'core', names: 'Figma|Sketch|Adobe Photoshop|Adobe Illustrator|Adobe After Effects|Adobe Premiere Pro|Blender|Framer|Webflow' },
    { categoryKey: 'design', kind: 'competency', tier: 'core', names: 'Product Design|UI Design|UX Design|UX Research|Interaction Design|Prototyping|Information Architecture|Design Systems|Service Design|Motion Design|Graphic Design|Typography|Visual Design|Accessibility Design|3D Design' },
    { categoryKey: 'design', kind: 'tool', tier: 'core', names: 'Adobe XD|Affinity Designer|Affinity Photo|Axure RP|Balsamiq|Canva|DaVinci Resolve|Lottie|ProtoPie|Rive|Spline|Zeplin' },
    { categoryKey: 'design', kind: 'tool', tier: 'extended', names: '3ds Max|Cinema 4D|Houdini|InVision|Maya|Principle|ZBrush' },
    { categoryKey: 'design', kind: 'competency', tier: 'extended', names: 'Content Design|Design Operations|User Testing' },
    { categoryKey: 'product', kind: 'competency', tier: 'core', names: 'Product Management|Product Strategy|Product Discovery|Product Roadmapping|Requirements Analysis|User Research|User Stories|Stakeholder Management|Program Management|Project Management|Technical Writing|Technical Product Management' },
    { categoryKey: 'product', kind: 'methodology', tier: 'core', names: 'Agile|Scrum|Kanban|Lean Startup|Design Thinking|OKRs|Shape Up' },
    { categoryKey: 'product', kind: 'tool', tier: 'core', names: 'Jira|Linear|Notion|Confluence|Asana|Trello|Monday.com|ClickUp' },
    { categoryKey: 'product', kind: 'tool', tier: 'extended', names: 'Aha!|Basecamp|Microsoft Planner|Productboard|Shortcut|Smartsheet' },
    { categoryKey: 'product', kind: 'competency', tier: 'extended', names: 'Product Operations|Product-Led Growth|Release Planning' },
    { categoryKey: 'analytics', kind: 'competency', tier: 'core', names: 'Data Analysis|Business Intelligence|Statistics|Data Visualization|Forecasting|Experiment Design|A/B Testing|Product Analytics|Marketing Analytics|Financial Analysis' },
    { categoryKey: 'analytics', kind: 'tool', tier: 'core', names: 'Microsoft Excel|Tableau|Microsoft Power BI|Looker|Metabase|Google Analytics|Amplitude|Mixpanel|Segment' },
    { categoryKey: 'analytics', kind: 'tool', tier: 'core', names: 'Adobe Analytics|Apache Superset|Heap|Looker Studio|Matomo|Mode|PostHog|Qlik Sense' },
    { categoryKey: 'analytics', kind: 'tool', tier: 'extended', names: 'Redash|ThoughtSpot' },
    { categoryKey: 'games', kind: 'platform', tier: 'core', names: 'Unity|Unreal Engine|Godot|OpenGL|Vulkan|DirectX|WebGL|ARKit|ARCore' },
    { categoryKey: 'games', kind: 'competency', tier: 'extended', names: 'Game Development|Game Design|Technical Art|Shader Programming|Virtual Reality|Augmented Reality|Spatial Computing|3D Modeling|Animation' },
    { categoryKey: 'games', kind: 'platform', tier: 'extended', names: 'Babylon.js|Bevy|Cocos2d-x|CryEngine|GameMaker|Metal|MonoGame|OpenXR|Phaser|Roblox Studio|WebGPU' },
    { categoryKey: 'scientific-engineering', kind: 'tool', tier: 'core', names: 'COMSOL Multiphysics|ANSYS|LabVIEW|Wolfram Mathematica|GNU Octave|KiCad|LTspice|FreeCAD|Autodesk Revit|Rhinoceros|Siemens NX' },
    { categoryKey: 'scientific-engineering', kind: 'tool', tier: 'extended', names: 'Abaqus|OpenFOAM|Simulink|SolidWorks|CATIA|Fusion 360|Altium Designer|Onshape|Autodesk Inventor|Grasshopper|PSpice|Proteus|Multisim|Modelica|OpenModelica|GNU Radio' },
    { categoryKey: 'scientific-engineering', kind: 'competency', tier: 'core', names: 'Scientific Computing|Numerical Methods|Finite Element Analysis (FEA)|Computational Fluid Dynamics (CFD)|Multiphysics Simulation|Computer-Aided Design (CAD)|Computer-Aided Engineering (CAE)|Computer-Aided Manufacturing (CAM)|Structural Analysis|Thermal Analysis|Electromagnetics Simulation|Circuit Simulation|Model-Based Design|Systems Engineering|Digital Twin|Design for Manufacturing|Additive Manufacturing' },
    { categoryKey: 'scientific-engineering', kind: 'domain', tier: 'core', names: 'Mechanical Engineering|Electrical Engineering|Civil Engineering|Chemical Engineering|Biomedical Engineering|Materials Science|Semiconductor Engineering|Renewable Energy Engineering' },
    { categoryKey: 'embedded', kind: 'platform', tier: 'core', names: 'Arduino|Raspberry Pi|ESP32|STM32|FreeRTOS|ROS|MQTT' },
    { categoryKey: 'embedded', kind: 'competency', tier: 'extended', names: 'Embedded Systems|Firmware Development|FPGA|Robotics|PCB Design|Industrial Automation|CAN Bus|Control Systems|Signal Processing' },
    { categoryKey: 'embedded', kind: 'platform', tier: 'extended', names: 'ArduPilot|BeagleBone|Buildroot|Gazebo|Mbed OS|NVIDIA Jetson|PlatformIO|PX4|Zephyr|Yocto' },
    { categoryKey: 'embedded', kind: 'protocol', tier: 'extended', names: 'I2C|Modbus|OPC UA|SPI|UART' },
    { categoryKey: 'blockchain', kind: 'platform', tier: 'core', names: 'Ethereum|Solana|Polygon|Foundry|Hardhat|Web3.js|Ethers.js' },
    { categoryKey: 'blockchain', kind: 'competency', tier: 'extended', names: 'Smart Contracts|Blockchain Development|DeFi|Tokenomics|Wallet Integration|Blockchain Security|Zero-Knowledge Proofs' },
    { categoryKey: 'blockchain', kind: 'platform', tier: 'extended', names: 'Alchemy|Aptos|Avalanche|Bitcoin|Cardano|Chainlink|Cosmos|Hyperledger Fabric|IPFS|Near Protocol|OpenZeppelin|Polkadot|Sui|The Graph|WalletConnect' },
    { categoryKey: 'enterprise', kind: 'platform', tier: 'core', names: 'Salesforce|SAP|ServiceNow|Microsoft Power Platform|Power Apps|Power Automate|UiPath|Zapier|Make|Airtable|Retool|Bubble' },
    { categoryKey: 'enterprise', kind: 'competency', tier: 'extended', names: 'Robotic Process Automation|Business Process Automation|Enterprise Architecture|Systems Integration|ERP|CRM Administration' },
    { categoryKey: 'enterprise', kind: 'platform', tier: 'extended', names: 'Adobe Commerce|Contentful|Freshworks|Magento|Microsoft Dynamics 365|NetSuite|Oracle ERP|Pipedrive|Sanity|Shopify|WooCommerce|Workday|Zendesk|Zoho CRM' },
    { categoryKey: 'growth', kind: 'competency', tier: 'core', names: 'SEO|Search Engine Marketing|Content Strategy|Content Marketing|Copywriting|Lifecycle Marketing|Email Marketing|Social Media Marketing|Community Management|Conversion Rate Optimization|Growth Strategy|Brand Strategy|Public Relations' },
    { categoryKey: 'growth', kind: 'tool', tier: 'extended', names: 'Google Ads|Meta Ads|HubSpot|Mailchimp|Semrush|Ahrefs|Hootsuite' },
    { categoryKey: 'growth', kind: 'tool', tier: 'extended', names: 'Braze|Buffer|Customer.io|Google Search Console|Klaviyo|Marketo|Moz|Optimizely|Sprout Social|VWO' },
    { categoryKey: 'business', kind: 'competency', tier: 'core', names: 'Sales|Business Development|Account Management|Customer Success|Customer Support|Lead Generation|Sales Operations|Financial Modeling|Accounting|Recruiting|People Operations|Procurement|Operations Management|Legal Operations|Business Strategy|Change Management' },
    { categoryKey: 'business', kind: 'tool', tier: 'extended', names: 'Intercom|QuickBooks|Salesloft|Stripe|Xero' },
    { categoryKey: 'human', kind: 'competency', tier: 'core', names: 'Communication|Collaboration|Leadership|Mentoring|Problem Solving|Critical Thinking|Facilitation|Presentation|Negotiation|Decision Making|Conflict Resolution|Time Management|Team Building|Adaptability|Creativity|Emotional Intelligence|Written Communication|Public Speaking' },
    { categoryKey: 'domain', kind: 'domain', tier: 'core', names: 'Fintech|Healthtech|Edtech|E-commerce|SaaS|Climate Tech|Cybersecurity|Automotive|Aerospace|Telecommunications|Media and Entertainment|Logistics|Retail|Manufacturing|Government|Real Estate|Insurance|Travel and Hospitality|Gaming Industry|Developer Tools' },
    { categoryKey: 'domain', kind: 'domain', tier: 'extended', names: 'Agritech|Biotechnology|Energy Technology|Legaltech|Proptech|Supply Chain Technology' },
    { categoryKey: 'programming', kind: 'language', tier: 'extended', names: 'AiScript|CoffeeScript|Forth|Haxe|LaTeX|Pkl|V|Vala|WebAssembly' },
    { categoryKey: 'frontend', kind: 'framework', tier: 'extended', names: 'Gatsby|GTK|Qt|Vuetify|Yew' },
    { categoryKey: 'frontend', kind: 'library', tier: 'extended', names: 'Apollo Client|p5.js|Pinia|Pug|ReactiveX|Windi CSS' },
    { categoryKey: 'backend', kind: 'framework', tier: 'extended', names: 'Elysia|Ktor|Rocket|Spring Framework' },
    { categoryKey: 'backend', kind: 'library', tier: 'extended', names: 'Discord.js|Hibernate' },
    { categoryKey: 'backend', kind: 'platform', tier: 'extended', names: 'ActiveMQ|Apache Camel|Appwrite|RabbitMQ' },
    { categoryKey: 'data', kind: 'platform', tier: 'extended', names: 'Anaconda|Apache Hive|Apache Solr' },
    { categoryKey: 'ai', kind: 'platform', tier: 'core', names: 'ChatGPT|Google Colab' },
    { categoryKey: 'cloud', kind: 'platform', tier: 'extended', names: 'Alibaba Cloud|OpenShift' },
    { categoryKey: 'developer-tools', kind: 'tool', tier: 'extended', names: 'Atom|CLion|CodePen|Emacs|Replit' },
    { categoryKey: 'devops', kind: 'tool', tier: 'extended', names: 'CMake' },
    { categoryKey: 'design', kind: 'tool', tier: 'extended', names: 'Ableton Live|Adobe Audition|Adobe Express|Adobe Firefly|AutoCAD|CapCut|GIMP|SketchUp' },
    { categoryKey: 'operating-systems', kind: 'platform', tier: 'core', names: 'Linux|macOS|ChromeOS|Arch Linux|Debian|Fedora|FreeBSD|Red Hat Enterprise Linux|Ubuntu|Windows|Windows Server' },
    { categoryKey: 'operating-systems', kind: 'platform', tier: 'extended', names: 'iPadOS|watchOS|tvOS|visionOS|Alpine Linux|BSD|HarmonyOS|NixOS|Plan 9|QNX|Solaris|Tizen' },
    { categoryKey: 'geospatial', kind: 'platform', tier: 'core', names: 'ArcGIS|GeoServer|Google Earth Engine|Mapbox|OpenStreetMap|QGIS' },
    { categoryKey: 'geospatial', kind: 'library', tier: 'core', names: 'GDAL|GeoPandas|Leaflet|PostGIS' },
] as const

const ALIASES: Readonly<Record<string, readonly string[]>> = {
    'JavaScript': ['JS', 'ECMAScript'],
    'TypeScript': ['TS'],
    'C#': ['C Sharp', 'CSharp'],
    'C++': ['C Plus Plus', 'CPP'],
    'F#': ['F Sharp', 'FSharp'],
    'React': ['React.js', 'ReactJS'],
    'Vue.js': ['Vue', 'VueJS'],
    'Next.js': ['NextJS', 'Next'],
    'Node.js': ['Node', 'NodeJS'],
    'Express': ['Express.js', 'ExpressJS'],
    'NestJS': ['Nest.js', 'Nest'],
    'Fastify': ['Fastify.js'],
    'React Native': ['RN'],
    'Tailwind CSS': ['Tailwind'],
    'GraphQL': ['GQL'],
    'PostgreSQL': ['Postgres', 'PostgreSQL DB'],
    'MongoDB': ['Mongo'],
    'Microsoft SQL Server': ['SQL Server', 'MSSQL'],
    'Amazon Web Services': ['AWS'],
    'Microsoft Azure': ['Azure'],
    'Google Cloud': ['GCP', 'Google Cloud Platform'],
    'Kubernetes': ['K8s'],
    'GitLab CI/CD': ['GitLab CI'],
    'GitHub Actions': ['GHA'],
    'Retrieval-Augmented Generation': ['RAG'],
    'Large Language Models': ['LLM', 'LLMs'],
    'Natural Language Processing': ['NLP'],
    'Identity and Access Management': ['IAM'],
    'CI/CD': ['Continuous Integration and Delivery'],
    'UI Design': ['User Interface Design'],
    'UX Design': ['User Experience Design', 'UI/UX Design', 'UI/UX'],
    'Search Engine Marketing': ['SEM'],
    'SEO': ['Search Engine Optimization'],
    'CRM Administration': ['CRM', 'Customer Relationship Management'],
    'Machine Learning': ['ML'],
    'Generative AI': ['GenAI', 'Gen AI'],
    'Site Reliability Engineering': ['SRE'],
    'Infrastructure as Code': ['IaC'],
    'End-to-End Testing': ['E2E Testing'],
    'A/B Testing': ['AB Testing', 'Split Testing'],
    '.NET MAUI': ['MAUI'],
    'Drizzle ORM': ['Drizzle', 'drizzle-orm'],
    'GitHub': ['Github', 'Git Hub'],
    'Visual Studio Code': ['VS Code', 'VSCode'],
    'IntelliJ IDEA': ['IntelliJ'],
    'Chrome Extension API': ['Chrome Extensions', 'Chrome API'],
    'WebExtensions API': ['Web Extensions', 'Browser Extension API'],
    'Vector Databases': ['Vector Database', 'Vector DB', 'Vector DBs'],
    'Sentence Transformers': ['SentenceTransformer', 'sentence-transformers'],
    'MiniLM': ['Mini LM', 'all-MiniLM-L6-v2'],
    'Embeddings': ['Embedding Models', 'Embedding Model', 'Sentence Embeddings', 'similar embedding model'],
    'Oracle Cloud Infrastructure': ['OCI'],
    'Red Hat Enterprise Linux': ['RHEL', 'Red Hat', 'CentOS', 'Rocky Linux', 'AlmaLinux'],
    'OpenShift': ['Red Hat OpenShift'],
    'p5.js': ['p5js'],
    'Windi CSS': ['WindiCSS'],
    'Cursor': ['Cursor AI'],
    'Codex': ['OpenAI Codex', 'Codex CLI', 'Codex App'],
    'Google Antigravity': ['Antigravity', 'Antigravity IDE', 'Antigravity CLI'],
    'Model Context Protocol': ['MCP'],
    'Agent2Agent Protocol': ['A2A', 'A2A Protocol'],
    'OpenAI Agents SDK': ['OpenAI Agents'],
    'Google Agent Development Kit': ['Google ADK', 'ADK'],
    'Amazon Bedrock Agents': ['Bedrock Agents'],
    'Azure AI Foundry': ['Azure AI Studio'],
    'App Store Connect': ['ASC'],
    'Swift Package Manager': ['SPM'],
    'macOS': ['Mac OS', 'Mac OS X', 'OS X'],
    'ChromeOS': ['Chrome OS'],
    'Claude': ['Anthropic API', 'Anthropic'],
    'Gemini': ['Google Gemini API', 'Gemini API'],
    'OpenAI API': ['OpenAI GPT', 'GPT', 'OpenAI'],
    'Debian': ['Raspberry Pi OS', 'Raspbian'],
    'BSD': ['OpenBSD', 'NetBSD'],
    'Linux': ['Gentoo', 'openSUSE', 'Oracle Linux', 'Amazon Linux', 'Asahi Linux', 'elementary OS', 'Linux Mint'],
    'COMSOL Multiphysics': ['COMSOL'],
    'ANSYS': ['Ansys', 'ANSYS Workbench'],
    'Wolfram Mathematica': ['Mathematica'],
    'GNU Octave': ['Octave'],
    'Siemens NX': ['NX CAD'],
    'Finite Element Analysis (FEA)': ['Finite Element Analysis', 'FEA'],
    'Computational Fluid Dynamics (CFD)': ['Computational Fluid Dynamics', 'CFD'],
    'Computer-Aided Design (CAD)': ['Computer Aided Design', 'CAD'],
    'Computer-Aided Engineering (CAE)': ['Computer Aided Engineering', 'CAE'],
    'Computer-Aided Manufacturing (CAM)': ['Computer Aided Manufacturing', 'CAM'],
    'Design for Manufacturing': ['DFM'],
}

export const SKILL_ICON_OVERRIDES: Readonly<Record<string, string>> = {
    'C#': 'csharp',
    'C++': 'cplusplus',
    'F#': 'fsharp',
    'Node.js': 'nodedotjs',
    'Next.js': 'nextdotjs',
    'Vue.js': 'vuedotjs',
    'Nuxt': 'nuxt',
    'Tailwind CSS': 'tailwindcss',
    'Material UI': 'mui',
    'shadcn/ui': 'shadcnui',
    'TanStack Query': 'reactquery',
    'D3.js': 'd3',
    'Three.js': 'threedotjs',
    'Amazon Web Services': 'amazonwebservices',
    'Microsoft Azure': 'microsoftazure',
    'Google Cloud': 'googlecloud',
    'GitHub Actions': 'githubactions',
    'GitLab CI/CD': 'gitlab',
    'Argo CD': 'argo',
    'Elastic Stack': 'elasticstack',
    'NGINX': 'nginx',
    'scikit-learn': 'scikitlearn',
    'Hugging Face': 'huggingface',
    'OpenAI API': 'openai',
    'Anthropic API': 'anthropic',
    'Google Gemini API': 'googlegemini',
    'Microsoft SQL Server': 'microsoftsqlserver',
    'Cloud Firestore': 'firebase',
    'Google BigQuery': 'googlebigquery',
    'Apache Kafka': 'apachekafka',
    'Apache Spark': 'apachespark',
    'Apache Airflow': 'apacheairflow',
    'Ruby on Rails': 'rubyonrails',
    'ASP.NET Core': 'dotnet',
    '.NET MAUI': 'dotnet',
    'Jetpack Compose': 'jetpackcompose',
    'Microsoft Power BI': 'powerbi',
    'Microsoft Excel': 'microsoftexcel',
    'Adobe Photoshop': 'adobephotoshop',
    'Adobe Illustrator': 'adobeillustrator',
    'Adobe After Effects': 'adobeaftereffects',
    'Adobe Premiere Pro': 'adobepremierepro',
    'Unreal Engine': 'unrealengine',
    'Raspberry Pi': 'raspberrypi',
    'Power Automate': 'powerautomate',
    'Google Analytics': 'googleanalytics',
    'Google Ads': 'googleads',
    'Meta Ads': 'meta',
    'GitHub': 'github',
    'Visual Studio Code': 'visualstudiocode',
    'Visual Studio': 'visualstudio',
    'IntelliJ IDEA': 'intellijidea',
    'PyCharm': 'pycharm',
    'WebStorm': 'webstorm',
    'PhpStorm': 'phpstorm',
    'Rider': 'rider',
    'Android Studio': 'androidstudio',
    'Xcode': 'xcode',
    'GitHub Copilot': 'githubcopilot',
    'Claude Code': 'claudecode',
    'Azure DevOps': 'azuredevops',
    'Chrome Extension API': 'googlechrome',
    'Chrome DevTools': 'googlechrome',
    'Chrome Web Store': 'googlechrome',
    'Firefox Add-ons': 'firefoxbrowser',
    'Safari Web Extensions': 'safari',
    'Oracle Cloud Infrastructure': 'oracle',
    'AWS SDK': 'amazonwebservices',
    'Azure SDK': 'microsoftazure',
    'Google Cloud SDK': 'googlecloud',
    'Drizzle ORM': 'drizzle',
    'MiniLM': 'huggingface',
    'all-MiniLM-L6-v2': 'huggingface',
    'Mistral AI': 'mistralai',
    'OpenAI GPT': 'openai',
    'Llama': 'meta',
    'Microsoft Teams': 'microsoftteams',
    'Google Workspace': 'google',
    'Stack Overflow for Teams': 'stackoverflow',
    'Near Protocol': 'near',
    'HTML': 'html5',
    'Bash': 'gnubash',
    'SwiftUI': 'swift',
    'SvelteKit': 'svelte',
    'Bun Runtime': 'bun',
    'Actix Web': 'actix',
    'Firebase Cloud Messaging': 'firebase',
    'Google Play Console': 'googleplay',
    'CockroachDB': 'cockroachlabs',
    'TimescaleDB': 'timescale',
    'Pydantic AI': 'pydantic',
    'Sentence Transformers': 'huggingface',
    'Gemini': 'googlegemini',
    'Google Cloud Run': 'googlecloud',
    'Swagger UI': 'swagger',
    'Lucidchart': 'lucid',
    'Docker Compose': 'docker',
    'Cargo': 'rust',
    'Pip': 'pypi',
    'Traefik': 'traefikproxy',
    'Storybook Test': 'storybook',
    'Lottie': 'lottiefiles',
    'Looker Studio': 'looker',
    'Qlik Sense': 'qlik',
    'ARKit': 'apple',
    'ESP32': 'espressif',
    'STM32': 'stmicroelectronics',
    'Ethers.js': 'ethers',
    'Lisp': 'commonlisp',
    'H2': 'h2database',
    'Zed': 'zedindustries',
    'Cocos2d-x': 'cocos',
    'Databricks Mosaic AI': 'databricks',
    'COMSOL Multiphysics': 'comsol',
    'ANSYS': 'ansys',
    'LabVIEW': 'labview',
    'Wolfram Mathematica': 'wolframmathematica',
    'GNU Octave': 'octave',
    'KiCad': 'kicad',
    'LTspice': 'ltspice',
    'FreeCAD': 'freecad',
    'Autodesk Revit': 'autodeskrevit',
    'Rhinoceros': 'rhinoceros',
    'Siemens NX': 'siemens',
}

export const SKILL_DEVICON_OVERRIDES: Readonly<Record<string, string>> = {
    'HTML': 'html5',
    'Java': 'java',
    'Bash': 'bash',
    'PowerShell': 'powershell',
    'Objective-C': 'objectivec',
    'Visual Basic': 'visualbasic',
    'SwiftUI': 'swift',
    'Android SDK': 'android',
    'Kotlin Multiplatform': 'kotlin',
    'React Native': 'reactnative',
    'SvelteKit': 'svelte',
    'Bun Runtime': 'bun',
    'Firebase Cloud Messaging': 'firebase',
    'Core Data': 'apple',
    'Room': 'android',
    'Firebase Realtime Database': 'firebase',
    'Amazon Web Services': 'amazonwebservices',
    'Amazon Bedrock': 'amazonwebservices',
    'Amazon RDS': 'amazonwebservices',
    'AWS Lambda': 'amazonwebservices',
    'AWS SDK': 'amazonwebservices',
    'Microsoft Azure': 'azure',
    'Azure AI': 'azure',
    'Azure Functions': 'azure',
    'Azure SDK': 'azure',
    'Azure Cosmos DB': 'cosmosdb',
    'Azure SQL Database': 'azuresqldatabase',
    'Azure DevOps': 'azuredevops',
    'Oracle Database': 'oracle',
    'Oracle Cloud Infrastructure': 'oracle',
    'Visual Studio Code': 'vscode',
    'Visual Studio': 'visualstudio',
    'JupyterLab': 'jupyter',
    'Microsoft Teams': 'microsoft',
    'Eclipse': 'eclipse',
    'Swagger UI': 'swagger',
    'Docker Compose': 'docker',
    'Cargo': 'rust',
    'Pip': 'pypi',
    'Traefik': 'traefikproxy',
    'Storybook Test': 'storybook',
    'Adobe Photoshop': 'photoshop',
    'Adobe Illustrator': 'illustrator',
    'Adobe After Effects': 'aftereffects',
    'Adobe Premiere Pro': 'premierepro',
    'Adobe XD': 'xd',
    'ARKit': 'apple',
    'ARCore': 'android',
    '3ds Max': 'threedsmax',
}

const KIND_ICON: Readonly<Record<SkillKind, SkillSemanticIconKey>> = {
    language: 'code-2',
    framework: 'boxes',
    library: 'library-big',
    database: 'database',
    platform: 'panels-top-left',
    tool: 'wrench',
    protocol: 'network',
    methodology: 'route',
    competency: 'badge-check',
    domain: 'landmark',
}

const SEMANTIC_ICON_OVERRIDES: Readonly<Record<string, SkillSemanticIconKey>> = {
    'Assembly': 'binary',
    'TestFlight': 'send',
    'AI Agents': 'bot',
    'AutoGen': 'bot',
    'CrewAI': 'bot',
    'Chroma': 'database-zap',
    'Machine Learning': 'brain-circuit',
    'Deep Learning': 'brain-circuit',
    'Generative AI': 'sparkles',
    'Large Language Models': 'message-square-text',
    'Retrieval-Augmented Generation': 'search-code',
    'Natural Language Processing': 'message-square-text',
    'Computer Vision': 'scan-eye',
    'Recommendation Systems': 'sparkles',
    'Prompt Engineering': 'message-square-text',
    'Model Evaluation': 'gauge',
    'Feature Engineering': 'sliders-horizontal',
    'MLOps': 'workflow',
    'Responsible AI': 'shield-check',
    'Embeddings': 'orbit',
    'Fine-Tuning': 'settings-2',
    'Foundation Models': 'boxes',
    'Multimodal AI': 'panels-top-left',
    'Synthetic Data': 'wand-sparkles',
    'Serverless Computing': 'cloud-lightning',
    'Edge Computing': 'network',
    'Cloud Architecture': 'cloud-cog',
    'Identity and Access Management': 'key-round',
    'Penetration Testing': 'bug',
    'Threat Modeling': 'radar',
    'Vulnerability Management': 'shield-alert',
    'Cryptography': 'key-round',
    'Digital Forensics': 'search',
    'Data Privacy': 'lock-keyhole',
    'Manual Testing': 'clipboard-check',
    'Test Automation': 'badge-check',
    'Unit Testing': 'test-tube-2',
    'Integration Testing': 'workflow',
    'End-to-End Testing': 'route',
    'Accessibility Testing': 'accessibility',
    'Performance Testing': 'gauge',
    'Load Testing': 'activity',
    'API Testing': 'network',
    'Product Design': 'pen-tool',
    'UI Design': 'pen-tool',
    'UX Design': 'mouse-pointer-2',
    'UX Research': 'search',
    'Interaction Design': 'mouse-pointer-2',
    'Prototyping': 'panels-top-left',
    'Motion Design': 'clapperboard',
    'Graphic Design': 'palette',
    '3D Design': 'box',
    'Product Management': 'map',
    'Project Management': 'calendar-range',
    'Agile': 'iteration-cw',
    'Scrum': 'iteration-cw',
    'Kanban': 'columns-3',
    'Data Analysis': 'chart-no-axes-combined',
    'Business Intelligence': 'chart-no-axes-combined',
    'Data Visualization': 'chart-no-axes-combined',
    'Game Development': 'gamepad-2',
    'Embedded Systems': 'circuit-board',
    'Firmware Development': 'cpu',
    'Robotics': 'bot',
    'Smart Contracts': 'scroll-text',
    'Blockchain Development': 'blocks',
    'SEO': 'search',
    'Communication': 'messages-square',
    'Collaboration': 'users-round',
    'Leadership': 'user-round-check',
    'Problem Solving': 'lightbulb',
    'Scientific Computing': 'orbit',
    'Numerical Methods': 'gauge',
    'Finite Element Analysis (FEA)': 'gauge',
    'Computational Fluid Dynamics (CFD)': 'gauge',
    'Multiphysics Simulation': 'orbit',
    'Computer-Aided Design (CAD)': 'pen-tool',
    'Computer-Aided Engineering (CAE)': 'circuit-board',
    'Computer-Aided Manufacturing (CAM)': 'wrench',
    'Structural Analysis': 'building-2',
    'Thermal Analysis': 'activity',
    'Electromagnetics Simulation': 'circuit-board',
    'Circuit Simulation': 'circuit-board',
    'Model-Based Design': 'boxes',
    'Systems Engineering': 'workflow',
    'Digital Twin': 'boxes',
    'Design for Manufacturing': 'wrench',
    'Additive Manufacturing': 'box',
    'Mechanical Engineering': 'wrench',
    'Electrical Engineering': 'circuit-board',
    'Civil Engineering': 'building-2',
    'Chemical Engineering': 'test-tube-2',
    'Biomedical Engineering': 'activity',
    'Materials Science': 'box',
    'Semiconductor Engineering': 'cpu',
    'Renewable Energy Engineering': 'cloud-lightning',
}

const CATEGORY_ICON = new Map(SKILL_CATEGORIES.map((category) => [category.key, category.iconKey]))

// Preserve identities when a skill is reclassified into a more accurate
// category. Assignments and external references continue to use the original
// canonical key while category filtering reflects the current taxonomy.
const CANONICAL_KEY_OVERRIDES: Readonly<Record<string, string>> = {
    Linux: 'devops.linux',
    visionOS: 'games.visionos',
}

function createDefinition(group: SkillGroup, name: string): MarketSkillDefinition {
    const slug = skillSlug(name)
    return {
        canonicalKey: CANONICAL_KEY_OVERRIDES[name] ?? `${group.categoryKey}.${slug}`,
        name,
        slug,
        categoryKey: group.categoryKey,
        kind: group.kind,
        marketTier: group.tier,
        aliases: [...(ALIASES[name] ?? [])],
        iconSource: 'lucide',
        iconKey: SEMANTIC_ICON_OVERRIDES[name] ?? KIND_ICON[group.kind] ?? CATEGORY_ICON.get(group.categoryKey) ?? 'badge',
        brandColor: null,
        description: null,
    }
}

export const MARKET_SKILLS: readonly MarketSkillDefinition[] = GROUPS.flatMap((group) =>
    group.names.split('|').map((name) => createDefinition(group, name.trim())),
)

const LOOKUP_INDEX = new Map<string, MarketSkillDefinition>()
for (const skill of MARKET_SKILLS) {
    for (const value of [skill.name, skill.slug, skill.canonicalKey, ...skill.aliases]) {
        const normalized = normalizeSkillLookup(value)
        if (normalized && !LOOKUP_INDEX.has(normalized)) LOOKUP_INDEX.set(normalized, skill)
    }
}

export const CORE_SKILLS = MARKET_SKILLS.filter((skill) => skill.marketTier === 'core')

export function findCatalogSkill(value: string): MarketSkillDefinition | null {
    return LOOKUP_INDEX.get(normalizeSkillLookup(value)) ?? null
}

export function searchMarketSkills(input: {
    query?: string
    category?: string | null
    kind?: SkillKind | null
    tier?: SkillMarketTier | null
    limit?: number
}): SkillSearchResult[] {
    const query = normalizeSkillLookup(input.query ?? '')
    const queryTokens = query.split(' ').filter(Boolean)
    const limit = Math.max(1, Math.min(100, Math.trunc(input.limit ?? 30)))
    const results: SkillSearchResult[] = []
    for (const skill of MARKET_SKILLS) {
        if (input.category && skill.categoryKey !== input.category) continue
        if (input.kind && skill.kind !== input.kind) continue
        if (input.tier && skill.marketTier !== input.tier) continue

        const name = normalizeSkillLookup(skill.name)
        const aliases = skill.aliases.map(normalizeSkillLookup)
        let score = skill.marketTier === 'core' ? 20 : 5
        let matchedAlias: string | null = null
        if (query) {
            if (name === query) score += 1000
            else if (aliases.includes(query)) {
                score += 900
                matchedAlias = skill.aliases[aliases.indexOf(query)] ?? null
            } else if (name.startsWith(query)) score += 600
            else if (aliases.some((alias) => alias.startsWith(query))) score += 500
            else if (name.includes(query)) score += 300
            else if (queryTokens.every((token) => name.includes(token) || aliases.some((alias) => alias.includes(token)))) score += 200
            else continue
        }
        results.push({ ...skill, score, matchedAlias })
    }
    return results.sort((a, b) => b.score - a.score || a.name.localeCompare(b.name)).slice(0, limit)
}

export const DEFAULT_ONBOARDING_SKILLS = [
    'React', 'Next.js', 'TypeScript', 'JavaScript', 'Python', 'Node.js',
    'PostgreSQL', 'Amazon Web Services', 'Docker', 'Kubernetes', 'Figma',
    'UX Design', 'Machine Learning', 'Data Analysis', 'Product Management',
    'Test Automation', 'Mobile Testing', 'Communication', 'Leadership', 'SEO',
].map((name) => findCatalogSkill(name)).filter((skill): skill is MarketSkillDefinition => Boolean(skill))

export const SKILL_RELATIONSHIP_PAIRS = [
    ['JavaScript', 'TypeScript', 'successor', 85], ['React', 'Next.js', 'ecosystem', 90],
    ['React', 'React Native', 'related', 75], ['Vue.js', 'Nuxt', 'ecosystem', 90],
    ['Svelte', 'SvelteKit', 'ecosystem', 90], ['Node.js', 'Express', 'ecosystem', 85],
    ['Node.js', 'NestJS', 'ecosystem', 85], ['Node.js', 'Fastify', 'ecosystem', 80],
    ['Python', 'Django', 'ecosystem', 85], ['Python', 'Flask', 'ecosystem', 85],
    ['Python', 'FastAPI', 'ecosystem', 85], ['Java', 'Spring Boot', 'ecosystem', 90],
    ['C#', 'ASP.NET Core', 'ecosystem', 90], ['Ruby', 'Ruby on Rails', 'ecosystem', 90],
    ['PHP', 'Laravel', 'ecosystem', 90], ['Swift', 'SwiftUI', 'ecosystem', 90],
    ['Kotlin', 'Jetpack Compose', 'ecosystem', 90], ['Dart', 'Flutter', 'ecosystem', 90],
    ['Docker', 'Kubernetes', 'commonly_used_with', 80], ['Kubernetes', 'Helm', 'ecosystem', 85],
    ['Kubernetes', 'Argo CD', 'commonly_used_with', 75], ['Terraform', 'Amazon Web Services', 'commonly_used_with', 70],
    ['Terraform', 'Microsoft Azure', 'commonly_used_with', 70], ['Terraform', 'Google Cloud', 'commonly_used_with', 70],
    ['Prometheus', 'Grafana', 'commonly_used_with', 90], ['PostgreSQL', 'pgvector', 'ecosystem', 90],
    ['PyTorch', 'Hugging Face', 'commonly_used_with', 75], ['Large Language Models', 'Retrieval-Augmented Generation', 'related', 85],
    ['Large Language Models', 'AI Agents', 'related', 80], ['Figma', 'Product Design', 'commonly_used_with', 70],
    ['Playwright', 'End-to-End Testing', 'related', 90], ['Cypress', 'End-to-End Testing', 'related', 90],
] as const
