// Generated by scripts/generate-skill-catalog.ts. Do not edit manually.
export const GENERATED_SKILL_ICON_THEME_ASSET_VARIANTS = {
  "skill-icons-nix-light": {
    "lightIconKey": "skill-icons-nix-light",
    "darkIconKey": "skill-icons-nix-dark",
    "rationale": "upstream-theme-pair"
  },
  "skill-icons-nextjs-light": {
    "lightIconKey": "skill-icons-nextjs-light",
    "darkIconKey": "skill-icons-nextjs-dark",
    "rationale": "upstream-theme-pair"
  },
  "skill-icons-emotion-light": {
    "lightIconKey": "skill-icons-emotion-light",
    "darkIconKey": "skill-icons-emotion-dark",
    "rationale": "upstream-theme-pair"
  },
  "skill-icons-dynamodb-light": {
    "lightIconKey": "skill-icons-dynamodb-light",
    "darkIconKey": "skill-icons-dynamodb-dark",
    "rationale": "upstream-theme-pair"
  },
  "skill-icons-vercel-light": {
    "lightIconKey": "skill-icons-vercel-light",
    "darkIconKey": "skill-icons-vercel-dark",
    "rationale": "upstream-theme-pair"
  },
  "skill-icons-aws-light": {
    "lightIconKey": "skill-icons-aws-light",
    "darkIconKey": "skill-icons-aws-dark",
    "rationale": "upstream-theme-pair"
  },
  "skill-icons-aiscript-light": {
    "lightIconKey": "skill-icons-aiscript-light",
    "darkIconKey": "skill-icons-aiscript-dark",
    "rationale": "upstream-theme-pair"
  },
  "skill-icons-pkl-light": {
    "lightIconKey": "skill-icons-pkl-light",
    "darkIconKey": "skill-icons-pkl-dark",
    "rationale": "upstream-theme-pair"
  },
  "skill-icons-elysia-light": {
    "lightIconKey": "skill-icons-elysia-light",
    "darkIconKey": "skill-icons-elysia-dark",
    "rationale": "upstream-theme-pair"
  },
  "skill-icons-ableton-light": {
    "lightIconKey": "skill-icons-ableton-light",
    "darkIconKey": "skill-icons-ableton-dark",
    "rationale": "upstream-theme-pair"
  },
  "skill-icons-linux-light": {
    "lightIconKey": "skill-icons-linux-light",
    "darkIconKey": "skill-icons-linux-dark",
    "rationale": "upstream-theme-pair"
  },
  "skill-icons-redhat-light": {
    "lightIconKey": "skill-icons-redhat-light",
    "darkIconKey": "skill-icons-redhat-dark",
    "rationale": "upstream-theme-pair"
  },
  "skill-icons-windows-light": {
    "lightIconKey": "skill-icons-windows-light",
    "darkIconKey": "skill-icons-windows-dark",
    "rationale": "upstream-theme-pair"
  },
  "skill-icons-plan9-light": {
    "lightIconKey": "skill-icons-plan9-light",
    "darkIconKey": "skill-icons-plan9-dark",
    "rationale": "upstream-theme-pair"
  }
} as const
