import type { Metadata } from "next";
import { LegalDocumentPage, LegalList } from "@/components/legal/LegalDocumentPage";
import { getLegalIdentity } from "@/lib/legal/config";
import { LEGAL_VERSIONS } from "@/lib/legal/versions";

export const metadata: Metadata = { title: "Data Processing Addendum | NetworkBase", description: "NetworkBase data-processing terms for eligible organisational customers." };

export default function DpaPage() {
  const i = getLegalIdentity();
  return <LegalDocumentPage eyebrow="Legal · Organisations" title="Data Processing Addendum" summary="Supplemental data-processing terms for an organisational customer that directs NetworkBase to process personal data on its behalf." version={LEGAL_VERSIONS.dpa} sections={[
    { id: "application", title: "1. Application and parties", content: <p>This addendum applies only when {i.operatorName} and an eligible organisational customer expressly agree that it forms part of their NetworkBase service agreement and the customer acts as controller or Data Fiduciary for personal data submitted to a managed workspace. It does not automatically apply to ordinary individual accounts or data for which NetworkBase independently determines purposes and means.</p> },
    { id: "instructions", title: "2. Instructions and roles", content: <p>The customer instructs NetworkBase to process covered data to provide, secure, support, and delete the contracted service, and as documented in product controls and support requests. Each party complies with the privacy law applicable to its role. NetworkBase will notify the customer if an instruction appears unlawful unless prohibited.</p> },
    { id: "details", title: "3. Processing details", content: <LegalList><li>Subject: collaborative project, profile, file, task, message, integration, support, and security processing.</li><li>Duration: the service term plus deletion, backup, legal, and security retention periods.</li><li>Data subjects: customer-authorised users, collaborators, invitees, and people described in customer content.</li><li>Data types: identity, contact, professional profile, project content, communications, device, audit, and integration data; regulated or sensitive data is not intended unless expressly agreed.</li></LegalList> },
    { id: "security", title: "4. Security and confidentiality", content: <p>NetworkBase maintains proportionate access control, authentication, encryption in transit, credential protection, logging, monitoring, recovery, vulnerability management, and incident procedures. Personnel and authorised contractors with access are bound by confidentiality duties.</p> },
    { id: "subprocessors", title: "5. Subprocessors and transfers", content: <p>The customer generally authorises the providers listed on the <a className="underline" href="/subprocessors">Subprocessors page</a>. NetworkBase remains responsible for imposing appropriate data-protection obligations on processors. Cross-border processing uses safeguards required by applicable law. A customer with a contractual notification right may object on reasonable data-protection grounds.</p> },
    { id: "assistance", title: "6. Requests, assessments and incidents", content: <p>Taking into account the nature of processing, NetworkBase will provide reasonable assistance with data-subject requests, security obligations, impact assessments, and regulator consultations. NetworkBase will notify the customer without undue delay after confirming a covered personal-data breach and provide available information needed for the customer’s duties.</p> },
    { id: "return", title: "7. Return and deletion", content: <p>During the account term, available exports provide portability. Following termination and the applicable grace period, NetworkBase deletes or anonymises covered data unless law requires retention. The customer is responsible for exporting required data before deletion and for copies in third-party services it controls.</p> },
    { id: "audit", title: "8. Information and audits", content: <p>NetworkBase will make reasonably necessary compliance information available. If that is insufficient, an agreed independent audit may occur no more than annually, during business hours, subject to confidentiality, security, scope, and cost protections, unless a regulator or confirmed incident reasonably requires otherwise.</p> },
    { id: "contact", title: "9. Contact and precedence", content: <p>Privacy requests: <a className="underline" href={`mailto:${i.privacyEmail}`}>{i.privacyEmail}</a>. If this addendum conflicts with the service Terms on processing covered data, this addendum controls; otherwise the Terms remain in effect. Mandatory law controls over both.</p> },
  ]} />;
}
