// Module barrel — re-exports from split modules
// crud: create, update, delete projects
// members: follow, bookmark, members, project groups
// queries: tasks, sprints, analytics

export {
    // CRUD
    createProjectAction,
    updateProject,
    deleteProject,
    deleteProjectDraftAction,
    updateProjectStageAction,
    updateProjectLifecycleAction,
    updateProjectSettingsAction,
    clearProjectCoverImageAction,
    createProjectCoverImageUploadUrlAction,
    finalizeProjectCoverImageUploadAction,
    getProjectAccessImpactAction,
    getProjectAccessTransitionPreflightAction,
    getProjectCollaboratorSettingsAction,
    getProjectDangerZonePreflightAction,
    getProjectFileWorkspaceSettingsAction,
    readProjectNotificationSettingsAction,
    readProjectMemberNotificationSettingsAction,
    getProjectMemberRemovalPreflightAction,
    getProjectSettingsAuditAction,
    archiveProjectAction,
    finalizeProjectAction,
    removeProjectMemberAction,
    retryGithubImportAction,
    updateProjectFileUploadDefaultsAction,
    updateProjectManualFileAnalyticsVisibilityAction,
    updateProjectMemberFileUploadAction,
    updateProjectNotificationSettingsAction,
    updateProjectMemberNotificationSettingsAction,
    updateProjectMemberRoleAction,
    updateProjectPublicTabVisibilityAction,
    updateProjectVisibilityAction,
    resetProjectNotificationSettingsAction,
    resetProjectMemberNotificationSettingsAction,

    // Members & Social
    ensureProjectGroupExists,

    toggleProjectFollowAction,
    getProjectMembersAction,
    getProjectLiveStatsAction,

    // Queries
    incrementProjectViewAction,
    readProjectDetailShell,
    readProjectDetailMetadata,
    fetchProjectTasksAction,
    fetchProjectSprintsAction,
    readProjectSprintDetail,
    readProjectSprintDetail as fetchProjectSprintDetailAction,
    fetchProjectSprintTimelinePageAction,
    fetchSprintTasksAction,
    getProjectTaskDetailAction,
    getProjectTaskActivityAction,
    getProjectAnalyticsAction,
    readProjectAnalyticsOverviewAction,
    readProjectAnalyticsMembersAction,
    readProjectMemberAnalyticsAction,
    readProjectAnalyticsWorkflowAction,
    readProjectAnalyticsSprintsAction,
    readProjectAnalyticsFilesAction,
    readProjectAnalyticsRisksAction,
    readProjectAnalyticsReportAction,
    readProjectAnalyticsSnapshotAction,
    readProjectAnalyticsTimelineAction,
    updateProjectAnalyticsRiskLifecycleAction,
    getProjectSyncStatus,

    // Task & Sprint CRUD
    createTaskAction,
    createSprintAction,
    updateSprintAction,
    deleteSprintAction,
    startSprintAction,
    completeSprintAction,
    moveTaskToSprintAction,
    deleteTaskAction,
} from './_all'

export {
    readProjectReadmeAction,
    readProjectReadmeDraftAction,
    saveProjectReadmeDraftAction,
    publishProjectReadmeAction,
    restoreProjectReadmeVersionAction,
    setProjectReadmePublishedVersionAction,
    deleteProjectReadmeVersionAction,
    discardProjectReadmeDraftAction,
    listProjectReadmeVersionsAction,
    validateProjectReadmeAction,
    readProjectReadmeReferenceOptionsAction,
    readProjectReadmeSmartBlockPreviewsAction,
    readProjectReadmeImportCandidatesAction,
    importProjectReadmeFromFileAction,
    applyProjectReadmeCreationIntentAction,
    createProjectReadmeAssetUploadUrlAction,
    finalizeProjectReadmeAssetUploadAction,
    deleteProjectReadmeAssetAction,
    readProjectReadmeSettingsAction,
    updateProjectReadmeSettingsAction,
} from './readme'

export {
    createProjectUpdateAction,
    createProjectUpdateCommentAction,
    deleteProjectUpdateAction,
    deleteProjectUpdateCommentAction,
    editProjectUpdateAction,
    readProjectUpdateAction,
    readProjectUpdateCommentsAction,
    readProjectUpdateContextOptionsAction,
    readProjectUpdatesAction,
    toggleProjectUpdateLikeAction,
    toggleProjectUpdatePinAction,
    readProjectUpdateDraftAction,
    saveProjectUpdateDraftAction,
    createProjectUpdateMediaUploadUrlAction,
    finalizeProjectUpdateMediaUploadAction,
    type ProjectUpdateCommentView,
    type ProjectUpdateMovementSummary,
    type ProjectUpdateView,
} from './updates'
