import type { Metadata } from "next";
import { LegalDocumentPage, LegalList } from "@/components/legal/LegalDocumentPage";
import { getLegalIdentity } from "@/lib/legal/config";
import { LEGAL_VERSIONS } from "@/lib/legal/versions";

export const metadata: Metadata = { title: "End User Licence Agreement | NetworkBase", description: "The licence for NetworkBase software and extensions." };

export default function EulaPage() {
  const i = getLegalIdentity();
  return <LegalDocumentPage eyebrow="Legal · Software licence" title="End User Licence Agreement" summary="This EULA grants a limited licence to use NetworkBase software, including its web client and any official browser or editor extension." version={LEGAL_VERSIONS.eula} sections={[
    { id: "licence", title: "1. Licence grant", content: <p>Subject to the Terms and this EULA, {i.operatorName} grants you a limited, revocable, non-exclusive, non-transferable, non-sublicensable licence to access and use the object-code form of NetworkBase software for lawful personal or internal business collaboration during your authorised use of the service.</p> },
    { id: "authorised-users", title: "2. Authorised users and devices", content: <p>You may use the software only through your own account or an account an organisation authorises you to use. You are responsible for devices, browsers, extensions, credentials, recovery codes, and users operating under your authority.</p> },
    { id: "ownership", title: "3. Ownership", content: <p>NetworkBase and its licensors own the software, interface, service marks, and platform materials. This EULA grants a licence, not a sale. You retain rights in your original project content. No provision transfers your code to NetworkBase or grants one collaborator ownership of another collaborator’s work.</p> },
    { id: "restrictions", title: "4. Restrictions", content: <LegalList><li>Do not copy, sell, rent, sublicense, distribute, or provide the software as a competing hosted service.</li><li>Do not reverse engineer, decompile, bypass access controls, extract source, or discover protected protocols except where mandatory law expressly permits it.</li><li>Do not scrape, benchmark for publication deceptively, overload, probe, exploit, or automate access outside documented interfaces.</li><li>Do not remove rights notices, impersonate the service, distribute modified clients as official, or use the software to violate the Acceptable Use Policy.</li></LegalList> },
    { id: "extensions", title: "5. Extensions, local data, and permissions", content: <p>An official extension may read or modify files you select, maintain device/session identifiers, keep local recovery copies, and optionally upload encrypted or access-controlled recovery drafts. Review requested permissions before installation. Local caches can remain on a device until you sign out, clear application data, uninstall the extension, or the configured retention process removes them.</p> },
    { id: "updates", title: "6. Updates and compatibility", content: <p>We may automatically update, patch, replace, or discontinue software to improve security, compatibility, or functionality. Updates may change permissions or minimum system requirements; material permission changes will be disclosed through the relevant installation or update channel.</p> },
    { id: "third-party", title: "7. Third-party and open-source software", content: <p>NetworkBase includes open-source and third-party components. Their licences and <a className="underline" href="/open-source">open-source notices</a> continue to apply and control where they expressly grant rights that this EULA cannot restrict. Google, GitHub, browser stores, operating systems, and extension marketplaces are separate providers with their own terms.</p> },
    { id: "content", title: "8. User content and integrations", content: <p>The software processes content only to provide features you invoke and according to the Privacy Policy. A licence to the client does not grant you rights to other users’ content, private projects, repository credentials, or platform data. External Git operations may remain after uninstalling or terminating the software.</p> },
    { id: "risk", title: "9. AI, code, and high-risk use", content: <p>You must review generated text, code changes, repository operations, commands, and recovered drafts. Do not use the software as the sole control for safety-critical, emergency, medical, weapons, infrastructure, financial execution, or other use where failure could cause death, personal injury, or substantial harm.</p> },
    { id: "termination", title: "10. Term and termination", content: <p>The licence begins when you accept this EULA and ends when your account or authorised access ends. On termination, stop using and remove installed clients. We may remotely invalidate sessions and service access. Local project files that you independently own are not transferred to us, but cached service data and protected client components must not be retained or used outside this licence.</p> },
    { id: "disclaimer", title: "11. Disclaimer and liability", content: <p>The software is provided “as available.” The disclaimers, liability limits, mandatory-rights safeguards, governing law, and dispute provisions in the Terms apply equally to this EULA. Nothing excludes a warranty or remedy that applicable law does not allow the parties to exclude.</p> },
    { id: "contact", title: "12. Contact and document priority", content: <p>Questions may be sent to <a className="underline" href={`mailto:${i.supportEmail}`}>{i.supportEmail}</a>. For software-licence conflicts, this EULA controls over the Terms; for service, privacy, content, payment, or community issues, the corresponding document controls. Mandatory law always prevails.</p> },
  ]} />;
}
