"use client";

export {
  useFilesWorkspaceStore,
  FILES_ROOT_KEY,
  filesParentKey,
  useFilesActions,
  useFilesProjectSlice,
  defaultWorkspace,
  symbolsEqual,
  FALLBACK_WORKSPACE,
  DEFAULT_PREFS,
  DEFAULT_GIT_STATE,
  DEFAULT_UI_STATE,
  ROOT_KEY,
  parentKey,
  contentKey,
  getFileContent,
  setFileContent,
  deleteFileContent,
  clearProjectContent,
  contentMapSize,
} from "./files";

export type {
  ExplorerSort,
  ExplorerMode,
  FilesViewMode,
  SavedExplorerView,
  EditorPreferences,
  WorkspaceTab,
  WorkspacePane,
  SoftLock,
  FileState,
  EditorSymbol,
  ProjectWorkspaceState,
  FilesWorkspaceState,
  GitState,
  UiState,
} from "./files/types";
