import type { Metadata } from "next";
import { LegalDocumentPage, LegalList } from "@/components/legal/LegalDocumentPage";
import { getLegalIdentity } from "@/lib/legal/config";
import { LEGAL_VERSIONS } from "@/lib/legal/versions";

export const metadata: Metadata = { title: "Terms of Service | NetworkBase", description: "The rules for using NetworkBase." };

export default function TermsPage() {
  const i = getLegalIdentity();
  const support = <a className="underline" href={`mailto:${i.supportEmail}`}>{i.supportEmail}</a>;
  const grievance = <a className="underline" href={`mailto:${i.grievanceEmail}`}>{i.grievanceEmail}</a>;
  return <LegalDocumentPage eyebrow="Legal · Agreement" title="Terms of Service" summary="These Terms govern accounts, collaboration, projects, messages, integrations, AI assistance, and public content on NetworkBase." version={LEGAL_VERSIONS.terms} sections={[
    { id: "agreement", title: "1. Agreement and operator", content: <p>These Terms form an electronic agreement between you and {i.operatorName}, operator of NetworkBase at {i.serviceAddress}. By creating an account or expressly accepting these Terms, you agree to them, the <a className="underline" href="/eula">EULA</a>, and the <a className="underline" href="/acceptable-use">Acceptable Use Policy</a>. The <a className="underline" href="/privacy">Privacy Policy</a> explains data processing and is not itself a waiver of privacy rights.</p> },
    { id: "eligibility", title: "2. Eligibility", content: <p>You must be at least 18 and legally capable of entering this agreement. If you use NetworkBase for an organisation, you confirm that you may bind it. You must provide accurate information and must not create an account for someone else without authority.</p> },
    { id: "accounts", title: "3. Accounts and security", content: <p>You are responsible for your credentials, connected providers, devices, recovery codes, and activity under your account. Notify {support} promptly of unauthorised access. We may require re-authentication, restrict a session, or suspend activity to protect users or the service.</p> },
    { id: "service", title: "4. The service", content: <p>NetworkBase provides professional profiles, project discovery, collaborative workspaces, documentation, files, tasks, messaging, notifications, GitHub workflows, recovery features, and optional AI assistance. Features may change, be limited, enter beta, or be discontinued. We do not promise uninterrupted availability or that every device, repository, file, integration, or browser will remain compatible.</p> },
    { id: "content", title: "5. Your content and licence", content: <><p>You retain ownership of content you lawfully create. You grant NetworkBase a worldwide, non-exclusive, royalty-free licence to host, copy, process, transmit, format, display, back up, and create technical derivatives of that content only as necessary to operate, secure, improve, and support the service and exercise your visibility and collaboration choices.</p><p>You confirm that you have the rights and permissions needed for everything you upload, import, share, or direct us to process. Public content may be viewed, linked, cached, indexed, or copied by others. Feedback about NetworkBase may be used without restriction or payment, but it will not include ownership of your project code.</p></> },
    { id: "projects", title: "6. Projects and collaborators", content: <LegalList><li>Project owners control visibility, roles, invitations, exports, integrations, archival, transfer, and deletion, subject to these Terms.</li><li>Members may access and modify content only within their assigned permissions and must respect confidential and personal information.</li><li>NetworkBase does not decide private ownership, employment, compensation, equity, or confidentiality disputes among collaborators.</li><li>Before leaving or deleting an account, owners should transfer projects that others need. Deletion may remove owned workspaces or conversations as disclosed in the interface.</li><li>A project privacy tab describes the current access state; it does not create a separate NDA or alter these Terms.</li></LegalList> },
    { id: "messages", title: "7. Communications and moderation", content: <p>Messages and project discussions are for lawful collaboration. Participants may report content. We may review reported or technically necessary information, restrict delivery, preserve evidence, remove content, or suspend accounts when reasonably necessary for safety, legal compliance, enforcement, or service integrity. Blocking changes future interaction but may not erase existing shared records.</p> },
    { id: "integrations", title: "8. GitHub and third-party services", content: <p>Connected services have separate terms. When you authorise GitHub operations, NetworkBase may create or modify repositories, branches, commits, pull requests, webhooks, and contributor attribution at your direction. These external actions may be public, copied, or difficult to reverse. You are responsible for repository permissions, licences, secrets, branch protection, review, and revoking access when no longer needed.</p> },
    { id: "ai", title: "9. AI-assisted features", content: <><p>AI output may be inaccurate, insecure, incomplete, offensive, or similar to other material. You must review output before publishing, executing, or relying on it. AI output is not legal, financial, medical, security, or other professional advice, and NetworkBase does not guarantee ownership, originality, fitness, or non-infringement.</p><p>You must have authority to submit prompts and source material and must not submit credentials or prohibited data. You remain responsible for content you accept, publish, or send to a repository and for any legally required disclosure that it was generated or modified using AI.</p></> },
    { id: "acceptable-use", title: "10. Acceptable use", content: <p>You must comply with the <a className="underline" href="/acceptable-use">Acceptable Use Policy</a>. Prohibited conduct includes illegal content, infringement, harassment, impersonation, sexual exploitation, malware, credential theft, unauthorised access, spam, deceptive automation, platform circumvention, and activity that harms users or infrastructure.</p> },
    { id: "confidentiality", title: "11. Confidential and regulated information", content: <p>NetworkBase is not an NDA, secret manager, health-record system, payment-card vault, or regulated professional repository. Do not upload secrets, credentials, classified material, special-category data, payment-card data, health records, or another person’s confidential information unless you have authority and the service expressly supports the required safeguards. Use project permissions carefully and maintain independent backups.</p> },
    { id: "ip-complaints", title: "12. Intellectual-property complaints", content: <p>If content infringes your rights, follow the <a className="underline" href="/copyright">Copyright and IP Complaint Process</a>. We may request identification, the work claimed, the exact NetworkBase location, good-faith statements, authority, and a signature. We may notify the affected user and allow a response where lawful.</p> },
    { id: "termination", title: "13. Suspension, termination, and deletion", content: <p>You may stop using the service and request deletion. We may restrict, suspend, or terminate access for material breach, risk, non-payment if paid services are introduced, legal requirements, or discontinued operation. Where appropriate, we will give notice and an opportunity to export or appeal. Provisions concerning ownership, licences already exercised, external actions, disputes, disclaimers, liability, indemnity, and lawful retention survive.</p> },
    { id: "warranties", title: "14. Disclaimers", content: <p>To the maximum extent permitted by law, NetworkBase is provided “as available” without promises that it will be uninterrupted, error-free, secure against every threat, or suitable for a particular project. Nothing in these Terms excludes mandatory consumer guarantees, fraud liability, or rights that cannot lawfully be excluded.</p> },
    { id: "liability", title: "15. Liability and indemnity", content: <><p>To the maximum extent permitted by law, neither party is liable for indirect, incidental, special, exemplary, or consequential loss, lost profits, lost opportunities, or lost data that was reasonably avoidable through backups. Any aggregate contractual cap will be the greater of amounts you paid to NetworkBase in the preceding 12 months or INR 5,000, except where a cap is prohibited by law.</p><p>You will defend and indemnify {i.operatorName} against third-party claims caused by your unlawful content, infringement, unauthorised integration activity, or material breach, but only to the extent permitted by law and after reasonable notice and control of the defence.</p></> },
    { id: "consumer", title: "16. Consumer rights and paid services", content: <p>NetworkBase currently does not describe a paid subscription in these Terms. If paid plans are introduced, price, billing period, taxes, renewal, cancellation, and refund terms will be shown before purchase. Mandatory consumer rights remain unaffected, and we will not use these Terms to impose an unfair waiver. Eligible organisational customers may separately agree to the <a className="underline" href="/dpa">Data Processing Addendum</a>.</p> },
    { id: "law", title: "17. Law, disputes, and grievances", content: <p>These Terms are governed by {i.governingLaw}, without overriding mandatory rights that apply where you live. Subject to those rights, disputes fall within {i.venue}. Before formal proceedings, contact {support}. Content or service grievances may be sent to {i.grievanceOfficer} at {grievance}. Regulatory and statutory complaint rights remain available.</p> },
    { id: "changes", title: "18. Changes and order of documents", content: <p>We will publish a new version and provide reasonable notice of material changes. We may request renewed acceptance before continued use. The EULA controls only software-licence issues; these Terms control other service issues; mandatory law prevails over both. Contact {support} for prior versions or questions.</p> },
  ]} />;
}
