import type { Metadata } from "next";
import { LegalDocumentPage, LegalList } from "@/components/legal/LegalDocumentPage";
import { getLegalIdentity } from "@/lib/legal/config";
import { LEGAL_VERSIONS } from "@/lib/legal/versions";

export const metadata: Metadata = {
  title: "Privacy Policy | NetworkBase",
  description: "How NetworkBase collects, uses, shares, retains, and protects personal data.",
};

export default function PrivacyPolicyPage() {
  const identity = getLegalIdentity();
  const contact = <a className="underline" href={`mailto:${identity.privacyEmail}`}>{identity.privacyEmail}</a>;
  const grievance = <a className="underline" href={`mailto:${identity.grievanceEmail}`}>{identity.grievanceEmail}</a>;

  return (
    <LegalDocumentPage
      eyebrow="Legal · Privacy"
      title="Privacy Policy"
      summary="This policy explains how NetworkBase handles information across profiles, collaborative projects, files, messages, integrations, AI assistance, notifications, and recovery features."
      version={LEGAL_VERSIONS.privacy}
      sections={[
        { id: "who-we-are", title: "1. Who we are", content: <><p>{identity.productName} is operated by {identity.operatorName}, with its service address at {identity.serviceAddress}. The operator determines how personal data is used for the NetworkBase service, except where it processes project data solely on behalf of an organisational customer.</p><p>Privacy questions and rights requests may be sent to {contact}. Complaints may be sent to {identity.grievanceOfficer} at {grievance}.</p></> },
        { id: "scope", title: "2. Scope", content: <p>This policy applies to networkbase.in, NetworkBase web applications, APIs, browser or editor extensions, project workspaces, messages, and related support. It does not replace the privacy terms of Google, GitHub, or another service you choose to connect.</p> },
        { id: "data", title: "3. Information we collect", content: <LegalList><li><strong>Account and identity:</strong> name, username, email, avatar, authentication identifiers, account status, and sign-in provider.</li><li><strong>Profile:</strong> biography, headline, pronouns, location, education, experience, skills, interests, availability, websites, and social links.</li><li><strong>Projects and work:</strong> projects, files, code, documentation, tasks, sprints, comments, updates, roles, applications, contributions, version history, deletion states, and recovery drafts.</li><li><strong>Communications:</strong> direct and group messages, attachments, reactions, edits, reports, read and delivery receipts, notifications, and limited presence or activity information.</li><li><strong>Integrations:</strong> Google and GitHub identifiers, GitHub repositories, branches, commits, pull requests, contributor identity and email metadata, encrypted access credentials, webhooks, and sync history.</li><li><strong>Device and operational data:</strong> IP-derived information, browser and device details, session identifiers, push endpoints, security events, audit records, request and error logs, and performance measurements.</li><li><strong>Location:</strong> a location you enter, approximate IP location, or coordinates you choose to provide for reverse geocoding.</li><li><strong>Support and legal:</strong> requests, complaints, reports, deletion reasons, evidence, and correspondence.</li></LegalList> },
        { id: "sources", title: "4. Where information comes from", content: <p>We receive information from you, other project participants, your device, connected services such as Google and GitHub, and activity generated while providing and securing the service. Contributor information may come from repository history or another member who invites, assigns, mentions, or reports you.</p> },
        { id: "purposes", title: "5. Why we use information", content: <LegalList><li>Provide accounts, profiles, projects, collaboration, messaging, search, notifications, recovery, export, and support.</li><li>Apply visibility, membership, role, block, and communication permissions.</li><li>Authenticate users, prevent abuse, rate-limit requests, preserve service integrity, investigate incidents, and comply with law.</li><li>Operate GitHub sync and other integrations at your direction.</li><li>Generate AI-assisted documentation only when requested.</li><li>Maintain, troubleshoot, measure, and improve reliability and accessibility.</li><li>Enforce our agreements and resolve complaints or ownership disputes.</li></LegalList> },
        { id: "grounds", title: "6. Grounds for processing", content: <p>Depending on applicable law, we process information to perform our contract with you, act on your requests, comply with legal obligations, protect users and the service, pursue proportionate legitimate interests, or with consent. Where consent is required, you may withdraw it as easily as it was given. Withdrawal does not affect earlier lawful processing.</p> },
        { id: "visibility", title: "7. Public, shared, and private information", content: <><p>Public profiles and public project tabs can be viewed without an account and may be copied, indexed, linked, or temporarily cached. Connection-only and private profile settings restrict the application view but do not recall copies previously shared.</p><p>Project owners and authorised members can access shared workspace content according to their roles. Messages are visible to conversation participants and authorised moderation or support personnel when necessary. Do not treat NetworkBase as a substitute for a confidentiality agreement.</p></> },
        { id: "ai", title: "8. AI assistance", content: <><p>When you request README or documentation completion, NetworkBase sends the submitted document context to Google Gemini and returns generated text. We record limited usage metrics and failures associated with your account but do not intentionally place prompt text in application logs.</p><p>Do not submit secrets, credentials, regulated data, or another person’s personal data unless you have authority. Provider retention or model-improvement treatment depends on the production Google service terms and account configuration.</p></> },
        { id: "location", title: "9. Location", content: <p>Location detection is optional. With browser permission, coordinates may be sent to OpenStreetMap Nominatim to obtain a city, state, and country. If precise location is unavailable, an IP-based request to ipapi.co may be used. The resulting location is not added to your profile until you choose to use or save it. You can edit or remove it later.</p> },
        { id: "providers", title: "10. Service providers and transfers", content: <><p>We use service providers to operate NetworkBase: Cloudflare for DNS, delivery, and security; Railway for application hosting; Supabase for authentication, database, storage, and realtime; Inngest for background jobs; Upstash for caching and rate limits; Google for sign-in and AI; GitHub for connected repositories; OpenStreetMap Nominatim and ipapi.co for optional location; and browser push services for notifications.</p><p>These providers may process data in other countries. We use contractual, technical, and organisational safeguards required by applicable law. A current operational list is maintained on the <a className="underline" href="/subprocessors">Subprocessors page</a>. We may also disclose information to professional advisers, a successor in a business transaction, or authorities when legally required.</p></> },
        { id: "storage", title: "11. Cookies and device storage", content: <p>NetworkBase uses essential cookies and browser storage for authentication, security, preferences, cached application state, offline messaging, and recovery. Optional analytics is used only when enabled in the deployed environment and, where required, after a valid choice. See the <a className="underline" href="/cookies">Cookie and storage notice</a>.</p> },
        { id: "retention", title: "12. Retention", content: <><p>We retain data only for its stated purpose and applicable legal, security, and dispute requirements. Current operational periods include:</p><LegalList><li>Account deletion: a 30-day cancellation period before application data is scheduled for permanent deletion.</li><li>Profile-read audit records: about 30 days; other profile/privacy activity audits: up to 365 days.</li><li>Onboarding telemetry: up to 90 days; extension session events: up to 180 days.</li><li>Dismissed notifications: about 30 days; read notifications: about 90 days; stale push subscriptions: about 60 days. Unread notifications remain while needed to deliver the service or until the account is deleted.</li><li>Extension recovery drafts: up to 30 days, limited to recent generations; clean-session drafts are generally removed after 24 hours.</li><li>Temporary GitHub import/sync snapshots: generally removed after completion or expiry unless referenced by a durable operation.</li><li>Security, registration, removed-content, transaction, and processing records: for the period required by applicable law, which may be 180 days, one year, or longer following a lawful preservation request.</li></LegalList><p>Deletion may not remove another participant’s records, de-identified records, legal evidence, backups awaiting rotation, public caches, or changes already sent to GitHub. We restrict retained data and erase or anonymise it when the exception ends.</p></> },
        { id: "rights", title: "13. Your choices and rights", content: <><p>Subject to applicable law, you may request access, correction, completion, export, deletion, restriction, objection, consent withdrawal, or information about recipients. You may also nominate another person where Indian law provides that right and complain to the appropriate regulator.</p><p>Use Settings for available controls and export/deletion, or contact {contact} for a complete request. We may verify identity and protect other people’s information before responding. If unresolved, contact {grievance}. When available under applicable law, you may also approach the Data Protection Board of India or another competent authority.</p></> },
        { id: "security", title: "14. Security and incidents", content: <p>We use access controls, encryption or token sealing where appropriate, private storage, logging, monitoring, rate limits, isolation, backups, and deletion jobs. No system is completely secure. If a personal-data breach requires notice, we will notify affected users and authorities with the information and timing required by law.</p> },
        { id: "children", title: "15. Children", content: <p>NetworkBase is intended for people aged 18 or older. Do not create an account if you are under 18. If we learn that a child’s data was submitted contrary to this rule, contact {contact}; we will investigate and delete or restrict it as required.</p> },
        { id: "deletion", title: "16. Account and project deletion", content: <p>Deleting an account first hides the profile and begins a 30-day grace period. Before deletion, project owners should transfer projects they want collaborators to retain and export needed information. Permanent deletion can affect owned projects, project conversations, connections, collections, recovery drafts, and authentication. GitHub commits, repositories, collaborator exports, and lawful retention copies are outside ordinary recall.</p> },
        { id: "changes", title: "17. Changes and contact", content: <><p>We publish an effective date and version. We will provide proportionate notice of material changes and request new contractual acceptance where appropriate. Earlier versions may be requested from {contact}.</p><p>Operator: {identity.operatorName}<br />Address: {identity.serviceAddress}<br />Privacy: {contact}<br />Grievance: {identity.grievanceOfficer}, {grievance}</p></> },
      ]}
    />
  );
}
